def madLibs():
    n1= input('noun: ')
    n2= input('noun: ')
    n3= input('noun: ')
    v1= input('verb ending in ing: ')
    n4= input('place: ')
    n5= input('part of the body: ')
    v2= input('action: ')
    n6= input('noun: ')
    v3= input('verb: ')
    n7= input('job title: ')
    n8= input('thing: ')
    n9= input('object: ')
    n10=input('noun: ')
    v4=input('verb ending in ed: ')
    n11=input('noun: ')
    v5= input('verb: ')
    n12=input('noun: \n')
    
    print ('There once was a little {} that liked to tell {}.' .format(n1,n2))
    print ('He said he saw a/an {} {} in its {}.'.format(n3,v1,n4))
    print ('I could not believe my {}!' .format(n5))
    print ('How dare he {} my {} without asking!' .format(v2,n6))
    print ('The first thing I did was {} the closest {} I could find in the {}.' .format(v3,n7,n8))
    print ('When he got here, I showed him my {} and told him to deal with it' .format(n9))
    print ('He instantly got his {} and {} the {} until it spoke' .format(n10,v4,n1))
    print ('The moral of the {} here is to make sure you always {} your {}' .format(n11,v5,n12))
    
def story2():
    
    obj = input('possesion: ')
    obj2 = input('object: ')
    plac = input('place: ')
    adj = input ('adjective: ')
    ver= input ('verb ending in ing: ')
    obje = input ('job: ')
    adj2 = input ('adjective: ')
    sta= input('statement: ')
    ver2= input('verb ending in ed: ')
    bod = input('part of body: ')
    bod2= input('part of body: ')
    noun= input('noun: ')
    noun2= input('noun: ')
    print ('The initial pain was gone as well as my {}, the fourteen year old and the {} he used to slash my arm.' .format(obj, obj2))
    print ('The other passengers waiting on the {} started to come to me and asked if I was {}.'.format(plac, adj))
    print ('As I {} to the floor I noticed the {} staff coming.' .format(ver, obje))
    print ('It was {} of me to try to resist I know now. All he said is “Hay {}, what’s up?”' .format(adj2, sta))
    print ('Before I could answer he {} my phone from my {}.' .format(ver2,bod))
    print ('I grabbed for him and thats when the {} swung around and caught my {}. ' .format(obj2,bod2))
    print ('He ran through the {} and was lost in the confusion. ' .format(noun))
    print ('I could not believe a {} could steal my stuff and get away with it!'.format(noun2))
    
def start():
    print ('pick a story')
    print ('Weird kid story: press 1')
    print ('robbery press 2')
    story = input('story: ')
    if story == '1': 
        madLibs()
    elif story == '2':    
        story2()
    else:
        print('Not a valid character')
start()