def madLibs():
    n1= input('noun')
    n2= input('noun')
    n3= input('noun')
    v1= input('verb ending in ing')
    n4= input('place')
    n5= input('part of the body')
    v2= input('action')
    n6= input('noun')
    v3= input('verb')
    n7= input('job title')
    n8= input('thing')
    n9= input('object')
    n10=input('noun')
    v4=input('verb ending in ed')
    n11=input('noun')
    v5= input('verb')
    n12=input('noun')
    
    print ('There once was a little {} that liked to tell {}.' .format(n1,n2))
    print ('He said he saw a/an {} {} in its {}.'.format(n3,v1,n4))
    print ('I could not believe my {}!' .format(n5))
    print ('How dare he {} my {} without asking!' .format(v2,n6))
    print ('The first thing I did was {} the closest {} I could find in the {}.' .format(v3,n7,n8))
    print ('When he got here, I showed him my {} and told him to deal with it' .format(n9))
    print ('He instantly got his {} and {} the {} until it spoke' .format(n10,v4,n1))
    print ('The moral of the {} here is to make sure you always {} your {}' .format(n11,v5,n12))
    
madLibs()